# Generated by Django 2.2.16 on 2020-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='chat',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
